### ISSUE TITLE
No module named 'taiga_contrib_mailchimp_subscription'

### ISSUE THREAD

**Issue by bentinata** [taigaio/taiga-contrib-mailchimp-subscription#2]
Thing I've tried.

`python -m pip install -ve "git+https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git@stable#egg=taiga-contrib-mailchimp-subscription&subdirectory=back`
`pip install -ve "git+https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git@stable#egg=taiga-contrib-mailchimp-subscription&subdirectory=back`
`pip3 install -ve "git+https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git@stable#egg=taiga-contrib-mailchimp-subscription&subdirectory=back`

Output:

```
Obtaining taiga-contrib-mailchimp-subscription from git+https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git@stable#egg=taiga-contrib-mailchimp-subscription&subdirectory=back
  Found command 'git' at '/usr/bin/git'
  https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git
  Clone in /home/taiga/.virtualenvs/taiga/src/taiga-contrib-mailchimp-subscription exists, and has correct URL (https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git)
  Updating /home/taiga/.virtualenvs/taiga/src/taiga-contrib-mailchimp-subscription clone (to stable)
  786810bbe02eeb9e3137d40b602fcde4b7ad9125 refs/heads/master
  786810bbe02eeb9e3137d40b602fcde4b7ad9125 refs/remotes/origin/HEAD
  786810bbe02eeb9e3137d40b602fcde4b7ad9125 refs/remotes/origin/master
  964c79e4d89675ee4a744b4b31729207746bbeaa refs/remotes/origin/stable
  d781da29e2d88038fb191a85cee49589d4e192aa refs/remotes/origin/us/65/user-resign
  a05a1751482a4d1c5e07d9c1f7ba357cab0cc13d refs/tags/1.10
  1489237cbd1186e31bcff7296a08535fc6137dc4 refs/tags/2.0
  8b8c709bad80f8c5874822659eb56e4712c36e45 refs/tags/2.1
  Running setup.py (path:/home/taiga/.virtualenvs/taiga/src/taiga-contrib-mailchimp-subscription/back/setup.py) egg_info for package taiga-contrib-mailchimp-subscription
    error in taiga-contrib-mailchimp-subscription setup command: Unable to import 'taiga_contrib_mailchimp_subscription': No module named 'taiga_contrib_mailchimp_subscription'
    Complete output from command python setup.py egg_info:
    error in taiga-contrib-mailchimp-subscription setup command: Unable to import 'taiga_contrib_mailchimp_subscription': No module named 'taiga_contrib_mailchimp_subscription'

----------------------------------------
Cleaning up...
  Removing temporary dir /home/taiga/.virtualenvs/taiga/build...
Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/src/taiga-contrib-mailchimp-subscription
Exception information:
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/taiga/.virtualenvs/taiga/src/taiga-contrib-mailchimp-subscription
```

`pip --version` output:

```
pip 1.5.4 from /home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages (python 3.4)
```

**Comment by bameda** [comment]
Your pip (1.5.4) is deprecated since 2014-05-03, the current version is 8.1.2 

Try this:

```
workon taiga
pip install --upgrade pip
pip install --upgrade setuptools
pip install -e "git+https://github.com/taigaio/taiga-contrib-mailchimp-subscription.git@stable#egg=taiga-contrib-mailchimp-subscription&subdirectory=back"

```
